# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca5be3de2ecb219216e36a2024058bc1f74bcdd0fa7e408265f3f6dc3abd4336fd8d0a0262e0efa2964c9326d9653914ddea47a096a5203557638b16a581e93c

test:
  secret_key_base: 0cd9ca4e0dbc82f5c51a680f72e7509990d89f6e75853d1ce2a7ff19c8d06b5ec971e591d465e42575bad32c9ef96c864657df715fabb7fc031b6b7a10d98e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
